all:
  children:
    spines:
      hosts:
        S1:
          ansible_host: 100.100.1.1
          router_id: 10.0.0.1
        S2:
          ansible_host: 100.100.1.2
          router_id: 10.0.0.2
    leafs:
      hosts:
        L3:
          ansible_host: 100.100.1.3
          router_id: 10.0.0.3
        L4:
          ansible_host: 100.100.1.4
          router_id: 10.0.0.4
        L5:
          ansible_host: 100.100.1.5
          router_id: 10.0.0.5
        L6:
          ansible_host: 100.100.1.6
          router_id: 10.0.0.6
        L7:
          ansible_host: 100.100.1.7
          router_id: 10.0.0.7
        L8:
          ansible_host: 100.100.1.8
          router_id: 10.0.0.8